
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic-net
    ulimits:                # permet de verrouiller la mémoire (pour éviter le swap)
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped

volumes:
  esdata:
    driver: local

networks:
  elastic-net:
    driver: bridge
