# Generated by Django 5.1.4 on 2025-01-16 09:56

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date d'achat"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("CONFIRMED", "Confirmé"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=10,
                        verbose_name="prix total",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="numéro de billet",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="events.event",
                        verbose_name="événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billet",
                "verbose_name_plural": "Billets",
                "ordering": ["-purchase_date"],
            },
        ),
    ]
