# Generated by Django 5.2 on 2025-08-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("CONFIRMED", "Confirmé"),
                    ("CANCELLED", "Annulé"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="status",
            ),
        ),
    ]
