# Generated by Django 5.1.4 on 2025-01-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Halls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="event_hall_images/default.jpg",
                        null=True,
                        upload_to="event_hall_images/",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="max hall seats", verbose_name="capacity"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Adress",
                        max_length=255,
                        verbose_name="location",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="show if hall is available",
                        verbose_name="active",
                    ),
                ),
            ],
            options={
                "verbose_name": "hall",
                "verbose_name_plural": "halls",
                "ordering": ["name"],
            },
        ),
    ]
